"""remove description from arcs

Revision ID: 675a6f5cea0f
Revises: 3541f17975db
Create Date: 2026-03-03 15:42:37.231263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675a6f5cea0f'
down_revision: Union[str, Sequence[str], None] = '3541f17975db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arcs', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arcs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
