"""add saga - quest relation

Revision ID: ddc1f4797951
Revises: b903a85907a3
Create Date: 2026-01-09 19:02:15.643941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc1f4797951'
down_revision: Union[str, Sequence[str], None] = 'b903a85907a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('saga_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_quests_saga_id'), 'quests', ['saga_id'], unique=False)
    op.create_foreign_key(None, 'quests', 'sagas', ['saga_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quests', type_='foreignkey')
    op.drop_index(op.f('ix_quests_saga_id'), table_name='quests')
    op.drop_column('quests', 'saga_id')
    # ### end Alembic commands ###
